from typing import List, Union, NoReturn, Iterable, Any, Tuple

__all__: List[str]
def get_verbosity() -> int: ...
def set_verbosity(level: int): ...

class HFile:
    mode: str
    name: Union[int, str]
    def __init__(self, name: Union[int, str], mode: str = ..., closefd: bool=...) -> None: ...
    def __enter__(self) -> HFile: ...
    def __exit__(self, type, value, tb) -> HFile: ...
    def __iter__(self) -> HFile: ...
    def __next__(self) -> str: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def fileno(self) -> int: ...
    def flush(self) -> None: ...
    def isatty(self) -> bool: ...
    def readable(self) -> bool: ...
    def read(self, size: int = ...) -> bytes: ...
    def readall(self) -> bytes: ...
    def readinto(self, buf: Any) -> bytes: ...
    def readline(self, size: int = ...) -> bytes: ...
    def readlines(self) -> List[bytes]: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def seekable(self) -> bool: ...
    def tell(self) -> int: ...
    def truncate(self, *args) -> NoReturn: ...
    def writable(self) -> bool: ...
    def write(self, b: bytes) -> int: ...
    def writelines(self, lines: Iterable[bytes]) -> None: ...

class HTSFile:
    closed: Any = ...
    description: Any = ...
    duplicate_filehandle: Any = ...
    filename: Any = ...
    index_filename: Any = ...
    is_bam: Any = ...
    is_bcf: Any = ...
    is_closed: Any = ...
    is_cram: Any = ...
    is_open: Any = ...
    is_read: Any = ...
    is_remote: Any = ...
    is_sam: Any = ...
    is_stream: Any = ...
    is_vcf: Any = ...
    is_write: Any = ...
    mode: Any = ...
    threads: Any = ...

    # @classmethod
    # def __init__(self, *args, **kwargs) -> None: ...
    def close(self) -> None: ...
    def check_truncation(self, ignore_truncation: bool = ...) -> None: ...
    @property
    def category(self) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def version(self) -> Tuple[int, int]: ...
    @property
    def compression(self) -> str: ...

    # WORKING HERE

    def add_hts_options(self, format_options = ...) -> Any: ...
    def get_reference_name(self, tid) -> Any: ...
    def get_tid(self, contig) -> Any: ...
    def is_valid_reference_name(self, contig) -> Any: ...
    def is_valid_tid(self, tid) -> Any: ...
    def parse_region(self, contig = ..., start = ..., stop = ..., region = ..., tid = ..., reference = ..., end = ...) -> Any: ...
    def reset(self) -> Any: ...
    def seek(self, uint64_toffset) -> Any: ...
    def tell(self) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, traceback) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
