from typing import Any, List, Type, Dict, Mapping, Sequence, Callable, Optional, Tuple, Union, IO

from pysam.libchtslib import HTSFile

__all__: List[str]

VALID_HEADER_TYPES: Dict[str, Type[Mapping]]
VALID_HEADERS: Sequence[str]
KNOWN_HEADER_FIELDS: Dict[str, Dict[str, Callable]]
VALID_HEADER_ORDER: Dict[str, Sequence[str]]

def build_header_line(fields: Any, record: str) -> str: ...

class AlignmentHeader:
    def __init__(self) -> None: ...
    @classmethod
    def _from_text_and_lengths(cls, text: Optional[str], reference_names: Optional[Sequence[str]], reference_lengths: Optional[Sequence[int]]) -> AlignmentHeader: ...
    @classmethod
    def from_text(cls, text: str) -> AlignmentHeader: ...
    @classmethod
    def from_dict(cls, header_dict: Dict[str, List[Any]]) -> AlignmentHeader: ...
    def _build_sequence_section(self) -> Any: ...
    # def as_dict(self) -> Any: ... deprecated
    def copy(self) -> Any: ...
    @classmethod
    def from_references(cls, reference_names, reference_lengths, text = ..., add_sq_text = ...) -> Any: ...
    def get_reference_length(self, reference: str) -> int: ...
    def get_reference_name(self, tid: int) -> Optional[str]: ...
    def get_tid(self, reference: str) -> int: ...
    def is_valid_tid(self, tid: int) -> bool: ...
    def to_dict(self) -> Any: ...

    @property
    def lengths(self) -> Tuple[int]: ...
    @property
    def nreferences(self) -> int: ...
    @property
    def references(self) -> Tuple[str]: ...

    # backwards compatibility
    def __getitem__(self, index) -> Any: ...
    def items(self) -> Any: ...
    #def iteritems(self) -> Any: ...
    #def keys(self) -> Any: ...
    #def values(self) -> Any: ...
    def get(self, *args) -> Any: ...
    def __len__(self) -> int: ...
    def __contains__(self, other) -> bool: ...

    def __bool__(self) -> bool: ...
    def __delitem__(self, other) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setitem__(self, index, object) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class AlignmentFile(HTSFile):
    @property
    def reference_filename(self) -> Optional[bytes]: ...
    @property
    def header(self) -> AlignmentHeader: ...


    lengths: Any = ...
    mapped: Any = ...
    nocoordinate: Any = ...
    nreferences: Any = ...
    references: Any = ...
    text: Any = ...
    unmapped: Any = ...


    def __init__(
        self,
        filepath_or_object: Union[str, IO, int],
        mode: Optional[str] = ..., # Literal["r", "w", "rb", "wb", "wh", "wbu", "rU", "wb0", "rc", "wc"]
        template: AlignmentFile = ...,
        reference_names: Optional[] = ...,
        reference_lengths=None,
        reference_filename=None,
        text=None,
        header=None,
        port=None,
        add_sq_text=True,
        add_sam_header=True,
        check_header=True,
        check_sq=True,
        index_filename=None,
        filepath_index=None,
        require_index=False,
        referencenames=None,
        referencelengths=None,
        duplicate_filehandle=True,
        ignore_truncation=False,
        format_options=None,
        threads: int = ...,
    ) -> None: ...
    @property
    def check_index(self) -> Any: ...
    def close(self) -> Any: ...
    def count(self, contig = ..., start = ..., stop = ..., region = ..., until_eof = ..., read_callback = ..., reference = ..., end = ...) -> Any: ...
    def count_coverage(self, contig, start = ..., stop = ..., region = ..., quality_threshold = ..., read_callback = ..., reference = ..., end = ...) -> Any: ...
    def fetch(self, contig = ..., start = ..., stop = ..., region = ..., tid = ..., until_eof = ..., multiple_iterators = ..., reference = ..., end = ...) -> Any: ...
    def find_introns(self, read_iterator) -> Any: ...
    def find_introns_slow(self, read_iterator) -> Any: ...
    def get_index_statistics(self) -> Any: ...
    def get_reference_length(self, reference) -> Any: ...
    def get_reference_name(self, tid) -> Any: ...
    def get_tid(self, reference) -> Any: ...
    def getrname(self, tid) -> Any: ...
    def gettid(self, reference) -> Any: ...
    def has_index(self) -> Any: ...
    def head(self, n, multiple_iterators = ...) -> Any: ...
    def is_valid_tid(self, inttid) -> Any: ...
    def mate(self, AlignedSegmentread) -> Any: ...
    def pileup(self, contig = ..., start = ..., stop = ..., region = ..., reference = ..., end = ..., **kwargs) -> Any: ...
    def write(self, AlignedSegmentread) -> int: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, exc_type, exc_value, traceback) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IndexStats(tuple):
    _asdict: Any = ...
    _field_defaults: Any = ...
    _fields: Any = ...
    _fields_defaults: Any = ...
    _replace: Any = ...
    __getnewargs__: Any = ...
    __slots__: Any = ...
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def _make(self, *args, **kwargs) -> Any: ...
    @property
    def contig(self) -> Any: ...
    @property
    def mapped(self) -> Any: ...
    @property
    def total(self) -> Any: ...
    @property
    def unmapped(self) -> Any: ...

class IndexedReads:
    def __init__(self, *args, **kwargs) -> None: ...
    def build(self) -> Any: ...
    def find(self, query_name) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorColumn:
    seq_len: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def addReference(self, FastaFilefastafile) -> Any: ...
    def add_reference(self, FastaFilefastafile) -> Any: ...
    def hasReference(self) -> Any: ...
    def has_reference(self) -> Any: ...
    def __iter__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorColumnAll(IteratorColumn):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorColumnAllRefs(IteratorColumn):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorColumnRegion(IteratorColumn):
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorRow:
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorRowAll(IteratorRow):
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorRowAllRefs(IteratorRow):
    def __init__(self, *args, **kwargs) -> None: ...
    def nextiter(self) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorRowHead(IteratorRow):
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorRowRegion(IteratorRow):
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class IteratorRowSelection(IteratorRow):
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class SNPCall:
    consensus_quality: Any = ...
    coverage: Any = ...
    genotype: Any = ...
    mapping_quality: Any = ...
    pos: Any = ...
    reference_base: Any = ...
    snp_quality: Any = ...
    tid: Any = ...
    @classmethod
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...
