name: CI

on: [push, pull_request]

jobs:
  sdist:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      #- run: sudo apt-get install libcurl4-openssl-dev
      - run: pip install Cython
      - name: Create sdist
        run: python setup.py sdist
      - name: Ensure sdist does not contain config.h
        run: "! tar -tf dist/pysam-*.tar.gz | grep '/config.h$'"
      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/pysam-*.tar.gz
          if-no-files-found: error
          retention-days: 1

  test:
    needs: [sdist]
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sdist
      - name: Install
        run: 'HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl" pip install -v pysam-*.tar.gz'
      - uses: actions/checkout@v2
      - name: Prepare test data
        run: |
          sudo apt-get install samtools bcftools tabix
          make -C tests/pysam_data
          make -C tests/cbcf_data
      - name: Install test dependencies
        run: python -m pip install pytest Cython  # Cython needed because one of the tests uses pyximport
      - run: pytest
